eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false

logging:
  level:
    root: warn