server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
        
        - id: course
          uri: lb://COURSE
          predicates:
            - Path=/course/**
          filters:
            - AuthenticationFilter

        - id: student
          uri: lb://STUDENT
          predicates:
            - Path=/student/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: video-service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/video/**
          filters:
            - AuthenticationFilter

        - id: video-stream
          uri: lb://VIDEO-STREAM
          predicates:
            - Path=/play/{videoId}/master-file
            - Path=/play/{videoId}/{quality}/m3u8
          filters:
            - AuthenticationFilter
                
        - id: video-stream-ts
          uri: lb://VIDEO-STREAM
          predicates:
            - Path=/play/{videoId}/{quality}/{segment}.ts

      discovery:
        locator:
          lower-case-service-id: true
  main:
    banner-mode: off

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: warn
