server:
  port: 8806

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/videoStreaming
    username: root
    password: 9135
  # jpa:
  #   open-in-view: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  main:
    banner-mode: off

video:
  path: /videos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: warn
