server:
  port: 8806

spring:
  config:
    import: COMMONS/application-common.yml, SECRETS/database_cred.yml
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

video:
  path: /videos
